"""Trading system state management using LangGraph patterns."""

from typing import TypedDict, Annotated, List, Dict, Optional, Any
from datetime import datetime, timedelta
from dataclasses import dataclass, field
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
import uuid

@dataclass
class TradingSignal:
    """Represents a trading signal generated by the system."""
    symbol: str
    action: str  # "buy", "sell", "hold"
    confidence: float  # 0.0 to 1.0
    price_target: Optional[float] = None
    stop_loss: Optional[float] = None
    quantity: Optional[float] = None
    reasoning: str = ""
    timestamp: datetime = field(default_factory=datetime.now)
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))

@dataclass
class RiskMetrics:
    """Portfolio risk metrics."""
    portfolio_value: float
    cash_available: float
    total_exposure: float
    concentration_risk: Dict[str, float]  # symbol -> % of portfolio
    var_1day: float = 0.0  # 1-day Value at Risk
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    volatility: float = 0.0

@dataclass
class MarketCondition:
    """Current market conditions assessment."""
    market_trend: str  # "bullish", "bearish", "sideways"
    volatility_regime: str  # "low", "medium", "high"
    sector_rotation: Dict[str, float]  # sector -> performance
    fear_greed_index: float = 50.0  # 0-100
    correlation_matrix: Dict[str, Dict[str, float]] = field(default_factory=dict)

class TradingState(TypedDict):
    """Central state for the trading system."""
    
    # Message history for agent communication
    messages: Annotated[List[BaseMessage], add_messages]
    
    # Portfolio and account information
    portfolio: Dict[str, Any]  # Current positions, cash, account info
    
    # Market data and analysis
    market_data: Dict[str, Any]  # Real-time and historical data
    market_conditions: Optional[MarketCondition]
    
    # Trading signals and decisions
    signals: List[TradingSignal]
    pending_orders: List[Dict[str, Any]]
    order_history: List[Dict[str, Any]]
    
    # Risk management
    risk_metrics: Optional[RiskMetrics]
    risk_limits: Dict[str, float]
    circuit_breakers: Dict[str, bool]
    
    # System status and metadata
    current_agent: str
    last_update: datetime
    session_id: str
    error_log: List[str]
    
    # Configuration and preferences
    trading_config: Dict[str, Any]
    watchlist: List[str]  # Symbols to monitor
    
    # Performance tracking
    pnl_history: List[Dict[str, Any]]
    trade_statistics: Dict[str, Any]

def create_initial_state(session_id: Optional[str] = None) -> TradingState:
    """Create initial trading state with default values."""
    
    if session_id is None:
        session_id = str(uuid.uuid4())
    
    return TradingState(
        messages=[],
        portfolio={
            "cash": 0.0,
            "equity": 0.0,
            "buying_power": 0.0,
            "positions": {},
            "day_trades": 0
        },
        market_data={},
        market_conditions=None,
        signals=[],
        pending_orders=[],
        order_history=[],
        risk_metrics=None,
        risk_limits={
            "max_position_size": 0.90,  # 90% of portfolio
            "max_daily_loss": 0.02,     # 2% daily loss limit
            "max_portfolio_risk": 0.01,  # 1% risk per trade
            "min_cash_reserve": 0.02,    # 2% cash reserve
            "max_correlation": 0.7,      # Max correlation between positions
            "max_sector_exposure": 0.3   # 30% max per sector
        },
        circuit_breakers={
            "market_volatility_high": False,
            "daily_loss_limit_hit": False,
            "position_size_exceeded": False,
            "correlation_risk_high": False
        },
        current_agent="market_monitor",
        last_update=datetime.now(),
        session_id=session_id,
        error_log=[],
        trading_config={
            "trading_mode": "paper",
            "update_frequency": 60,  # seconds
            "strategies_enabled": ["mean_reversion", "trend_following"],
            "risk_tolerance": "moderate"
        },
        watchlist=["SPY", "QQQ", "AAPL", "MSFT", "GOOGL"],  # Default watchlist
        pnl_history=[],
        trade_statistics={
            "total_trades": 0,
            "winning_trades": 0,
            "losing_trades": 0,
            "avg_win": 0.0,
            "avg_loss": 0.0,
            "win_rate": 0.0,
            "profit_factor": 0.0
        }
    )

def update_state_timestamp(state: TradingState) -> TradingState:
    """Update the last_update timestamp in state."""
    state["last_update"] = datetime.now()
    return state

def add_signal_to_state(state: TradingState, signal: TradingSignal) -> TradingState:
    """Add a new trading signal to state."""
    state["signals"].append(signal)
    # Keep only last 100 signals to prevent memory bloat
    if len(state["signals"]) > 100:
        state["signals"] = state["signals"][-100:]
    return update_state_timestamp(state)

def add_error_to_state(state: TradingState, error: str) -> TradingState:
    """Add error message to state log."""
    timestamp = datetime.now().isoformat()
    state["error_log"].append(f"{timestamp}: {error}")
    # Keep only last 50 errors
    if len(state["error_log"]) > 50:
        state["error_log"] = state["error_log"][-50:]
    return update_state_timestamp(state)

def set_circuit_breaker(state: TradingState, breaker_name: str, 
                       active: bool = True) -> TradingState:
    """Set or clear a circuit breaker."""
    state["circuit_breakers"][breaker_name] = active
    return update_state_timestamp(state)

def is_trading_halted(state: TradingState) -> bool:
    """Check if any circuit breakers are active."""
    return any(state["circuit_breakers"].values())

def update_portfolio_state(state: TradingState, portfolio_data: Dict[str, Any]) -> TradingState:
    """Update portfolio information in state."""
    state["portfolio"].update(portfolio_data)
    return update_state_timestamp(state)

def update_market_data_state(state: TradingState, symbol: str, 
                           data: Dict[str, Any]) -> TradingState:
    """Update market data for a specific symbol."""
    if "symbols" not in state["market_data"]:
        state["market_data"]["symbols"] = {}
    
    state["market_data"]["symbols"][symbol] = data
    return update_state_timestamp(state)

def get_active_signals(state: TradingState, max_age_minutes: int = 30) -> List[TradingSignal]:
    """Get recent active signals within the specified time window."""
    cutoff_time = datetime.now() - timedelta(minutes=max_age_minutes)
    return [
        signal for signal in state["signals"] 
        if signal.timestamp > cutoff_time and signal.action != "hold"
    ]

def calculate_position_exposure(state: TradingState) -> Dict[str, float]:
    """Calculate current position exposure by symbol."""
    positions = state["portfolio"].get("positions", {})
    portfolio_value = state["portfolio"].get("equity", 1.0)
    
    if portfolio_value <= 0:
        return {}
    
    exposure = {}
    for symbol, position in positions.items():
        market_value = position.get("market_value", 0)
        exposure[symbol] = abs(market_value) / portfolio_value
    
    return exposure

def validate_state(state: TradingState) -> List[str]:
    """Validate state consistency and return any issues found."""
    issues = []
    
    # Check required fields
    required_fields = ["portfolio", "signals", "risk_limits", "session_id"]
    for field in required_fields:
        if field not in state:
            issues.append(f"Missing required field: {field}")
    
    # Check portfolio data
    if "portfolio" in state:
        portfolio = state["portfolio"]
        required_portfolio_fields = ["cash", "equity", "buying_power"]
        for field in required_portfolio_fields:
            if field not in portfolio:
                issues.append(f"Missing portfolio field: {field}")
            elif not isinstance(portfolio[field], (int, float)):
                issues.append(f"Portfolio field {field} should be numeric")
    
    # Check risk limits
    if "risk_limits" in state:
        risk_limits = state["risk_limits"]
        for limit_name, limit_value in risk_limits.items():
            if not isinstance(limit_value, (int, float)):
                issues.append(f"Risk limit {limit_name} should be numeric")
            elif limit_value < 0:
                issues.append(f"Risk limit {limit_name} should be non-negative")
    
    return issues